#+TITLE: Emacs Pretty Personal Portable Configuration
#+AUTHOR: Diacus Mágnuz
#+STARTUP: logdrawer

EP3C (Emacs Pretty Personal Portable Configuration) is a modular,
batteries-included Emacs configuration. It uses =use-package= for
declarative package management and organizes settings into independent
modules written in Org mode.

Modules are loaded via =org-babel-load-file= and can be enabled or
disabled through Emacs' customization interface.

See the settings [[file:src/modules/*.org][here]].

* Installation
  To install the settings, load =src/install.el= and call =(ep3c--setup)=:

  #+begin_src emacs-lisp :results none
    (load-file (file-name-concat default-directory "src" "install.el"))
    (ep3c--setup)
  #+end_src

  When installation is done, =*Customize Option: Ep3c Modules*= buffer
  will display, you can select the modules you want to load from there.

  Once the Ep3c Modules option is ready for you, restart Emacs the way
  you usually do.

* Remove configuration
  To get rid of everything just delete =user-emacs-directory=
  #+name: remove-everything
  #+begin_src emacs-lisp :results none
    (delete-directory user-emacs-directory t t)
  #+end_src

  To delete the settings but keep the rest, only delete =init.el= file
  and =modules= folder.

  #+name: delete-settings-only
  #+begin_src emacs-lisp :results none
    (delete-file (file-name-concat user-emacs-directory "init.el"))
    (delete-directory (file-name-concat user-emacs-directory "modules") t)
  #+end_src
