#+TITLE: Haskell settings
#+AUTHOR: Diacus Magnuz
* Haskell mode
The [[https://wiki.haskell.org/Emacs][haskell-mode]] package is a set of major modes for writing Haskell
code and working with Haskell projects. Features syntax hightlighting,
intelligent indentation, interaction with inferior Haskel interpreter,
code browsing, and Cabal project integration. It supports Hugs, GHCi,
Cabal, hslint, hoogle, cabal-dev and other utilities. See the [[http://haskell.github.io/haskell-mode/manual/latest/][Haskell
Mode manual]] for more details.

The *haskell-mode* includes an specialized /compilation mode/ with
additional features called [[http://haskell.github.io/haskell-mode/manual/latest/Compilation.html#Compilation][haskell-compile]]. When invoked it tries to
guess how to compile the program associated to the current buffer.

#+begin_src emacs-lisp
  (defun haskell-mode-key-bindings (mode-map)
    "Define convenient key-bindings for Haskell mode"
    (evil-define-key '(normal visual motion)
      mode-map
      (kbd "SPC o r")
      'haskell-interactive-bring)
    (evil-define-key '(normal visual motion)
      mode-map
      (kbd "SPC c c")
      'haskell-compile))

  (use-package haskell-mode
    :ensure t
    :hook ((haskell-mode . eglot-ensure)
           (haskell-mode . (lambda ()
                             (haskell-mode-key-bindings
                              haskell-mode-map)))
           (haskell-cabal-mode . (lambda ()
                                   (haskell-mode-key-bindings
                                    haskell-cabal-mode-map)))))
#+end_src

* Haskell Language Server
The [[https://haskell-language-server.readthedocs.io/en/latest/what-is-hls.html][Haskell Language Server (HLS)]] provides LSP support for Haskell.
Eglot has built-in support - just ensure =haskell-language-server= is
installed system-wide.

#+begin_src emacs-lisp
  ;; Eglot handles Haskell automatically via haskell-language-server
  ;; No additional configuration needed - the hook above enables eglot-ensure
  ;;
  ;; Install HLS:
  ;;   - ghcup install hls
  ;;   - or: cabal install haskell-language-server
#+end_src