#+TITLE: Orgmode settings
#+AUTHOR: Diacus Magnuz
* General settings
  Jump to heading, as describes at [[https://stackoverflow.com/questions/15011703/is-there-an-emacs-org-mode-command-to-jump-to-an-org-heading][Stackoverflow]]
  #+begin_src emacs-lisp
    ;; Basic settings
    (setq org-goto-interface 'outline-path-completion
          org-goto-max-level 10
          org-outline-path-complete-in-steps nil
          org-src-window-setup 'other-frame)


    ;; Disable flycheck in =org-src= mode
    (add-hook 'org-src-mode-hook (lambda () (flycheck-mode -1)))
  #+end_src

  Include =.org.gpg= files in =org-agenda-files= following [[https://emacs.stackexchange.com/questions/36542/include-org-gpg-files-in-org-agenda][StackExchange
  (emacs) answer]]

  #+begin_src emacs-lisp
    (unless (string-match-p "\\.gpg" org-agenda-file-regexp)
      (setq org-agenda-file-regexp "\\`[^.].*\\.org\\\(\\.gpg\\\)?\\'"))
  #+end_src
* Org Agenda
  Sometimes I need to focus only in one or a few org agenda topics,
  these functions help out manipulate =org-agenda-files= list easily.

* Key bindings
  | Bind key      | to function   |
  |---------------+---------------|
  | =SPC= =o= =a= | =org-agenda=  |
  | =SPC= =o= =c= | =org-capture= |

  #+begin_src emacs-lisp
    (evil-define-key 'normal 'global
      (kbd "SPC o a") #'org-agenda)
    (evil-define-key 'normal 'global
      (kbd "SPC o c") #'org-capture)
  #+end_src

* Evil Org
  [[https://github.com/Somelauw/evil-org-mode][evil-org]] package adds key-bindings to Emacs org-mode
  #+begin_src emacs-lisp
    (use-package evil-org
      :ensure t
      :after org
      :hook (org-mode . evil-org-mode)
      :config
      (require 'evil-org-agenda)
      (evil-org-agenda-set-keys))
  #+end_src

  If Emacs runs inside a terminal, =TAB= key might not work as expected
  (being bound to =evil-jump-forward= instead of =org-tab= or
  =org-cycle=).

  #+begin_src emacs-lisp
    (add-hook 'org-mode-hook
	      (lambda ()
		;; Only apply this in terminal mode
		(unless (display-graphic-p)
		  ;; Prevent Evil from binding C-i (Tab) to evil-jump-forward
		  (setq evil-want-C-i-jump nil)
		  ;; Bind TAB to org-cycle in normal state
		  (evil-define-key 'normal 'global (kbd "TAB") 'org-cycle))))
  #+end_src

* Org modern
  [[https://github.com/minad/org-modern][org-modern]] provides modern styling for Org buffers using font
  locking and text properties. It replaces both org-bullets and
  org-superstar with actively maintained code.

  #+begin_src emacs-lisp
    (use-package org-modern
      :ensure t
      :after org
      :hook (org-mode . org-modern-mode)
      :config
      ;; Thinner table lines for better cursor visibility
      (setq org-modern-table-vertical 1
            org-modern-table-horizontal 0.05))
  #+end_src

* Heading faces
  Custom font scaling for org headings.

  #+begin_src emacs-lisp
    (custom-theme-set-faces
     'user
     '(org-level-8 ((t (:inherit default :height 1.0))))
     '(org-level-7 ((t (:inherit default :height 1.0))))
     '(org-level-6 ((t (:inherit default :height 1.0))))
     '(org-level-5 ((t (:inherit default :height 1.0))))
     '(org-level-4 ((t (:inherit default :height 1.1))))
     '(org-level-3 ((t (:inherit default :height 1.25))))
     '(org-level-2 ((t (:inherit default :height 1.5))))
     '(org-level-1 ((t (:inherit default :height 1.75))))
     '(org-document-title ((t (:inherit default :height 2.0 :underline nil)))))
  #+end_src

* Orgmode babel
  Org [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][Babel]] supports a growing number of programming languages.
  #+begin_src emacs-lisp
    (use-package ob-restclient
      :ensure t)

    (org-babel-do-load-languages
     'org-babel-load-languages
     '((awk        . t)
       (dot        . t)
       (haskell    . t)
       (js         . t)
       (python     . t)
       (restclient . t)
       (shell      . t)
       (sql        . t)
       (sqlite     . t)))
  #+end_src

* Org utils
  #+begin_src emacs-lisp
    (use-package org-utils
      :quelpa (org-utils :fetcher github :repo "diacus/org-utils"))
  #+end_src
