#+TITLE: Orgmode settings
#+AUTHOR: Diacus Magnuz
* General settings
  Jump to heading, as describes at [[https://stackoverflow.com/questions/15011703/is-there-an-emacs-org-mode-command-to-jump-to-an-org-heading][Stackoverflow]]
  #+begin_src emacs-lisp
    ;; Basic settings
    (setq org-goto-interface 'outline-path-completion
          org-goto-max-level 10
          org-outline-path-complete-in-steps nil
          org-src-window-setup 'other-frame)

    ;; Enable indent mode
    (add-hook 'org-mode-hook (lambda () (org-indent-mode 1)))

    ;; Disable flycheck in org-src mode (only if flycheck is loaded)
    (add-hook 'org-src-mode-hook
              (lambda ()
                (when (bound-and-true-p flycheck-mode)
                  (flycheck-mode -1))))
  #+end_src

  Include =.org.gpg= files in =org-agenda-files= following [[https://emacs.stackexchange.com/questions/36542/include-org-gpg-files-in-org-agenda][StackExchange
  (emacs) answer]]

  #+begin_src emacs-lisp
    (unless (string-match-p "\\.gpg" org-agenda-file-regexp)
      (setq org-agenda-file-regexp "\\`[^.].*\\.org\\\(\\.gpg\\\)?\\'"))
  #+end_src

* TODO Keywords
  Custom TODO keywords with semantic faces (theme-agnostic):
  - TODO :: Things selected to do at some point (shadow, light)
  - NEXT :: Things selected to do in the short term (warning, normal)
  - WORK :: Things in progress (success, bold)
  - WAIT :: Things in progress but waiting some event (error, bold)
  - DONE :: Things completed (success, strikethrough)
  - KILL :: Things canceled (shadow, strikethrough)

  #+begin_src emacs-lisp
    (setq org-todo-keywords
          '((sequence "TODO(t)" "NEXT(n)" "WORK(i)" "WAIT(w)" "|" "DONE(d)" "KILL(k)")))

    ;; Faces for agenda view (org-modern doesn't apply there)
    (setq org-todo-keyword-faces
          '(("TODO" . (:inherit shadow :weight light))
            ("NEXT" . (:inherit warning :weight normal))
            ("WORK" . (:inherit success :weight bold))
            ("WAIT" . (:inherit error :weight bold))
            ("DONE" . (:inherit success :strike-through t))
            ("KILL" . (:inherit shadow :strike-through t))))
  #+end_src

* Org Agenda
  Sometimes I need to focus only in one or a few org agenda topics,
  these functions help out manipulate =org-agenda-files= list easily.

* Key bindings
  | Bind key | to function |
  |----------+-------------|
  | =SPC= =o= =a=  | =org-agenda=  |
  | =SPC= =o= =c=  | =org-capture= |

  #+begin_src emacs-lisp
    (evil-define-key 'normal 'global
      (kbd "SPC o a") #'org-agenda)
    (evil-define-key 'normal 'global
      (kbd "SPC o c") #'org-capture)
  #+end_src

* Evil Org
  [[https://github.com/Somelauw/evil-org-mode][evil-org]] package adds key-bindings to Emacs org-mode
  #+begin_src emacs-lisp
    (use-package evil-org
      :ensure t
      :after org
      :hook (org-mode . evil-org-mode)
      :config
      (require 'evil-org-agenda)
      (evil-org-agenda-set-keys))
  #+end_src

  If Emacs runs inside a terminal, =TAB= key might not work as expected
  (being bound to =evil-jump-forward= instead of =org-tab= or
  =org-cycle=).

  #+begin_src emacs-lisp
    (add-hook 'org-mode-hook
	      (lambda ()
		;; Only apply this in terminal mode
		(unless (display-graphic-p)
		  ;; Prevent Evil from binding C-i (Tab) to evil-jump-forward
		  (setq evil-want-C-i-jump nil)
		  ;; Bind TAB to org-cycle in normal state
		  (evil-define-key 'normal 'global (kbd "TAB") 'org-cycle))))
  #+end_src

* Look and feel
  Take ideas from [[https://zzamboni.org/post/beautifying-org-mode-in-emacs/][Beautifying Org Mode in Emacs]] blog post
  #+begin_src emacs-lisp
    (setq org-hide-emphasis-markers t)

    (font-lock-add-keywords 'org-mode
    			'(("^ *\\([-]\\) "
    			   (0 (prog1 ()
    				(compose-region (match-beginning 1)
    						(match-end 1)
    						"•"))))))

    (custom-theme-set-faces
     'user
     '(org-level-8 ((t (:inherit default :height 1.0))))
     '(org-level-7 ((t (:inherit default :height 1.0))))
     '(org-level-6 ((t (:inherit default :height 1.0))))
     '(org-level-5 ((t (:inherit default :height 1.0))))
     '(org-level-4 ((t (:inherit default :height 1.1))))
     '(org-level-3 ((t (:inherit default :height 1.25))))
     '(org-level-2 ((t (:inherit default :height 1.5))))
     '(org-level-1 ((t (:inherit default :height 1.75))))
     '(org-document-title ((t (:inherit default :height 2.0 :underline nil))))
     '(org-block ((t (:inherit fixed-pitch))))
     '(org-code ((t (:inherit (shadow fixed-pitch)))))
     '(org-document-info ((t (:foreground "dark orange"))))
     '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
     '(org-indent ((t (:inherit (org-hide fixed-pitch)))))
     '(org-link ((t (:foreground "royal blue" :underline t))))
     '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     '(org-property-value ((t (:inherit fixed-pitch))) t)
     '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     '(org-table ((t (:inherit fixed-pitch :foreground "#83a598"))))
     '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.8))))
     '(org-verbatim ((t (:inherit (shadow fixed-pitch))))))
  #+end_src
** Org bullets
  #+begin_src emacs-lisp
    (use-package org-bullets
      :ensure t
      :after org)

    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
  #+end_src

** Org modern
   [[https://github.com/minad/org-modern][org-modern]] for modern styling of timestamps, tags, progress, and TODO
   keywords. Bullet styling is disabled to allow org-bullets to handle
   heading markers.
   #+begin_src emacs-lisp
     (use-package org-modern
       :ensure t
       :after org
       :hook (org-mode . org-modern-mode)
       :config
       ;; Disable bullet styling - let org-bullets handle it
       (setq org-modern-star nil
             org-modern-hide-stars nil
             org-modern-table nil
             org-modern-block-name nil)

       ;; Per-keyword TODO faces for org-modern (all 4 chars for uniform box width)
       (setq org-modern-todo-faces
             '(("TODO" . (:inherit shadow :weight light :box (:line-width -1)))
               ("NEXT" . (:inherit warning :weight normal :box (:line-width -1)))
               ("WORK" . (:inherit success :weight bold :box (:line-width -1)))
               ("WAIT" . (:inherit error :weight bold :box (:line-width -1)))
               ("DONE" . (:inherit success :strike-through t :box (:line-width -1)))
               ("KILL" . (:inherit shadow :strike-through t :box (:line-width -1)))))

       ;; Modern faces for various elements
       ;; Removed :height so they scale with heading levels
       (custom-theme-set-faces
        'user
        '(org-modern-label ((t (:inherit fixed-pitch))))
        '(org-modern-date-active ((t (:inherit (org-date fixed-pitch) :box (:line-width -1)))))
        '(org-modern-date-inactive ((t (:inherit (org-date fixed-pitch shadow) :box (:line-width -1)))))
        '(org-modern-time-active ((t (:inherit (org-date fixed-pitch) :box (:line-width -1)))))
        '(org-modern-time-inactive ((t (:inherit (org-date fixed-pitch shadow) :box (:line-width -1)))))
        '(org-modern-tag ((t (:inherit (fixed-pitch shadow) :box (:line-width -1)))))
        '(org-modern-todo ((t (:inherit (org-todo fixed-pitch) :box (:line-width -1)))))
        '(org-modern-done ((t (:inherit (org-done fixed-pitch) :box (:line-width -1)))))
        '(org-modern-priority ((t (:inherit fixed-pitch :box (:line-width -1)))))
        '(org-modern-progress ((t (:inherit fixed-pitch)))))

       ;; Agenda styling
       (setq org-agenda-tags-column 0
             org-agenda-block-separator ?─
             org-agenda-time-grid
             '((daily today require-timed)
               (800 1000 1200 1400 1600 1800 2000)
               " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
             org-agenda-current-time-string
             "⭠ now ─────────────────────────────────────────────────"))
   #+end_src

* Orgmode babel
  Org [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][Babel]] supports a growing number of programming languages.
  #+begin_src emacs-lisp
    (use-package ob-restclient
      :ensure t)

    (org-babel-do-load-languages
     'org-babel-load-languages
     '((awk        . t)
       (dot        . t)
       (haskell    . t)
       (js         . t)
       (python     . t)
       (restclient . t)
       (shell      . t)
       (sql        . t)
       (sqlite     . t)))
  #+end_src

* Org utils
  #+begin_src emacs-lisp
    (use-package org-utils
      :quelpa (org-utils :fetcher github :repo "diacus/org-utils"))
  #+end_src