#+TITLE: Secrets and encryption
#+AUTHOR: Diacus Magnuz

* GnuPG
Setting the value of =epg-pinentry-mode= to =loopback= allows Emacs to
query the passphrase throught minibuffer.
#+begin_src emacs-lisp
  (setq epg-pinentry-mode 'loopback)
#+end_src

* Windows Wrapper
Since *GNU* =pass= is the standard *UNIX* password store, When working on
Windows, better install password-store within WSL and write a wrapper
around it.

Write a sample wrapper like the listed below and save it under the the
name =pass.cmd= inside a directory listed in the =Path= environment
variable, then set the =password-store-executable= variable

#+begin_example powershell
  @echo off
  wsl --exec pass %*
#+end_example

In this scenario, the detection of *PASSWORD_STORE_DIR* fails because
Windows doesn't autodetect it within *WSL* So we should tell it where it
is.

The package [[https://git.zx2c4.com/password-store/tree/contrib/emacs/password-store.el][password-store.el]] uses the =password-store-dir= function to
point to the password store root directory. In order to point to the
right directory, the best approach is set =auth-source-pass-filename= to
the right location.

#+begin_src emacs-lisp
  (defun wsl--get-user ()
    "Return the user name name from WSL."
    (string-trim
     (shell-command-to-string
      "wsl.exe sh -lc 'printf %s \"$USER\"'")))


  (defun wsl--get-distro ()
    "Return the default WSL distro name."
    (let ((coding-system-for-read 'utf-16-le))
      (string-trim
       (shell-command-to-string
        "wsl.exe -l -q"))))


  (defun wsl--get-password-store ()
    "Return the Windows UNC path to the WSL password store."
    (let* ((distro (wsl--get-distro))
           (user   (wsl--get-user)))
      (format "//wsl$/%s/home/%s/.password-store"
              distro user)))
#+end_src
* Password management
GNU [[https://www.passwordstore.org][pass]] is a tool that makes password management simple by following
the [[http://en.wikipedia.org/wiki/Unix_philosophy][UNIX philosophy]].

With =pass= each password lives inside of a =gpg= encrypted text file,
which make it easy to share between devices.

Emacs [[https://github.com/stuartsierra/password-store/tree/master/contrib/emacs][password-store.el]] is a package that provides functions for
working with GNU pass.

#+begin_src emacs-lisp
  (use-package pass :ensure t)
  (use-package password-store
    :ensure t
    :init
    (when (eq system-type 'windows-nt)
      ; Set the correct value to read the password-store inside WSL
      (setq auth-source-pass-filename (wsl--get-password-store))))
#+end_src

