#+TITLE: Python Settings
#+AUTHOR: Diacus Mágnuz

* Virtual environments
Use [[https://github.com/aiguofer/pyenv.el][pyenv.el]] to manage your Python version within Emacs using pyenv

** Load order requirement
Pyvenv must be loaded before elpy because elpy requires pyvenv during
initialization. If pyvenv is not available when elpy loads, it throws
"Cannot open load file: No such file or directory, pyvenv".

#+begin_src emacs-lisp
  (use-package pyenv
    :quelpa (pyenv :fetcher github :repo "aiguofer/pyenv.el")
    :hook (python-mode . global-pyenv-mode))

  (use-package pyvenv
    :ensure t
    :hook ((python-mode . pyvenv-mode)))
#+end_src

* Elpy
Elpy (see the [[https://elpy.readthedocs.io/en/latest/index.html][docs]] for details) is the Emacs Python Development
Environment. It aims to provide an easy to install, fully-featured
environment for Python development.

** Configuration notes
- The =:after pyvenv= ensures pyvenv is loaded before elpy initializes,
  preventing "Cannot open load file" errors.
- No manual =load= calls for elpy components are needed; elpy handles
  its own module loading internally. Manual loads caused native
  compilation warnings because functions from other elpy files (elpy-pdb,
  elpy-nav, etc.) were not known during compilation.

#+begin_src emacs-lisp
  (use-package elpy
    :ensure t
    :after pyvenv
    :init
    (advice-add 'python-mode :before 'elpy-enable))

  (add-hook 'python-mode-hook #'lsp)
#+end_src

* Debugging
#+begin_src emacs-lisp
  (use-package dap-python
    :ensure nil
    :after python
    :init
    (setq dap-python-debugger 'debugpy))
#+end_src

