#+TITLE: Personal Emacs Configuration
#+AUTHOR: Diacus Magnuz
#+STARTUP: overview

* Melpa Repositories
  There are other URL alternatives for this, replace it as you need
  - https://stable.melpa.org/packages/
  - https://melpa.milkbox.net/packages/

  #+begin_src emacs-lisp :results none
    (require 'package)

    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
    (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
    (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/") t)

    ; activate all the packages (in particular autoloads)
    (package-initialize)
    (package-refresh-contents)
  #+end_src

* Saving Customizations
  In the customization buffer, you can _save_ a customization setting
  by choosing the ='Save for Future Sessions'= choice from its
  ='[State]'= button. The =C-x= =C-s= (=Custom-save=) command, or
  ='[Apply and Save]'= button at the top of the customization buffer,
  saves all applicable settings in the buffer.

  Saving works by writing code to a file, usually your initialization
  file. Future Emacs sessions will automatically read this file at
  startup, which sets up the customizations again.

  The following code block tells Emacs to use a different file than
  the default =$HOME/.emacs.d/init.el=.

  #+begin_src emacs-lisp :results none
    (setq custom-file "~/.config/emacs/custom.el")
    (load custom-file)
  #+end_src

* Install Selected Packages
  #+begin_src emacs-lisp :results none
    (package-install-selected-packages)
  #+end_src

* Evil mode
  Enable Vi layer and define a toggle function attaching the =M-u= key
  binding. The original solution is hosted [[http://makble.com/how-to-toggle-evil-mode-in-emacs][here]].

  #+begin_src emacs-lisp :results none
    (require 'evil)
    (evil-mode 1)

    (defun evil-mode-toggle ()
      (interactive)
      (if (bound-and-true-p evil-local-mode)
          (progn (evil-local-mode (or -1 1))
                 (set-variable 'cursor-type 'bar))
          (progn (evil-local-mode (or 1 1))
                 (set-variable 'cursor-type 'box))))

    (global-set-key (kbd "M-u") 'evil-mode-toggle)
  #+end_src

* Org-mode
** Refiling
*** How do we split things up?
    Of course we could hold everything on the same file but it is more
    convinient to have it split in several files depending the king of
    activity they organize. We need to customize three variables for
    an elegant refiling.

**** org-refile-targets
     This defines where refiling can place items. If this variable is
     set to "nil" then refiling only happens in the current
     buffer. For my propose I need to set it to =org-agenda-files
     :max-level . 2= which means that the items can be places in all
     agenda files below headlines of level 1 and 2.
     
**** org-refile-use-outline-path
     This need to be set to /"file"/ which means we see the t arget
     path including the file name of the Org-file where we want to put
     the item in.
     
**** org-refile-allow-creating-parent-nodes
     This defines if we are allowed to create new parent headlines in
     the target file. We set this to the value /"confirm"/ which asks
     for confirmation if the target we entered would create a new
     headline.
   
*** Refiling process
    As seen we also need to define =org-agenda-files= now because
    =org-refile-targets= is using this list to determine in which
    files items can be placed. So at the moment we set it to
    /"work.org"/, /"personal.org"/, and so on...

    #+begin_src emacs-lisp :results none
      (setq org-agenda-files
            '("~/org/sunpower.org"
             "~/org/wizeline.org"
             "~/org/personal.org"
             "~/org/training.org"))
    #+end_src

** Focus agenda
   Some times I need to only see agenda for one topic

   #+begin_src emacs-lisp :results none
     (defun org-focus-personal () "Set focus on private stuff"
            (interactive)
            (setq org-agenda-files '("~/org/personal.org")))

     (defun org-focus-training () "Set focus on training rutines"
            (interactive)
            (setq org-agenda-files '("~/org/training.org")))

     (defun org-focus-sunpower () "Set focus on sunpower stuff"
            (interactive)
            (setq org-agenda-files '("~/org/sunpower.org")))

     (defun org-focus-wizeline () "Set focus on wizeline stuff"
            (interactive)
            (setq org-agenda-files '("~/org/wizeline.org")))

     (defun org-focus-okr () "Set focus on wizeline okr stuff"
            (interactive)
            (setq org-agenda-files '("~/org/okr.org")))

     (defun org-focus-wizeline+okr () "Set focus on work stuff"
            (interactive)
            (setq org-agenda-files '("~/org/wizeline.org" "~/org/okr.org")))

     (defun org-focus-work () "Set focus on work stuff"
            (interactive)
            (setq org-agenda-files '("~/org/sunpower.org" "~/org/wizeline.org" "~/org/okr.org")))

     (defun org-focus-all () "Set focus on all things"
            (interactive)
            (setq org-agenda-files '("~/org/personal.org"
                                     "~/org/wizeline.org"
                                     "~/org/sunpower.org"
                                     "~/org/okr.org"
                                     "~/org/training.org")))
   #+end_src

** MobileOrg with Dropbox
   1. Define a local directory for Org documents: =~/org=
   2. Define a file for mobile notes
   3. Set a dropbox directory =~/Dropbox/org=


   #+begin_src emacs-lisp
     (setq org-directory "~/org"
           org-mobile-inbox-for-pull "~/org/flagged.org"
           org-mobile-directory "~/Dropbox/org")
   #+end_src

** Link PDF files
   Define a new link type and attach a function to handle it. The
   original solution comes from [[https://emacs.stackexchange.com/questions/30344/how-to-link-and-open-a-pdf-file-to-a-specific-page-skim-adobe][stackexchange]].

   The idea is to process the Link to find out the number of page so
   we can link specific parts of the document.

   #+begin_src emacs-lisp
     (require 'org)

     (org-add-link-type "pdf" 'org-pdf-open nil)

     (defun org-pdf-open (link)
            "open [pdf file]"
            (start-process 'open link))
   #+end_src

** Enabling different languages for code blocks
   The mapping ~C-c C-c~ by default prompts to ask confirmation prior
   execution, it is safe but anoying...

   #+begin_src emacs-lisp :results none
     (setq org-confirm-babel-evaluate nil)
   #+end_src

   JSON is not a programming language, however we can define an
   executor function to evaluate data in this format:

   #+begin_src emacs-lisp :results none
     (defun org-babel-execute:json (body params)
       (let ((jq (cdr (assoc :jq params)))
             (node (cdr (assoc :node params))))
         (cond
          (jq
           (with-temp-buffer
             ;; Insert the JSON into the temp buffer
             (insert body)
             ;; Run jq command on the whole buffer, and replace the buffer
             ;; contents with the result returned from jq
             (shell-command-on-region (point-min) (point-max) (format "jq -r \"%s\"" jq) nil 't)
             ;; Return the contents of the temp buffer as the result
             (buffer-string)))
          (node
           (with-temp-buffer
             (insert (format "const it = %s;" body))
             (insert node)
             (shell-command-on-region (point-min) (point-max) "node -p" nil 't)
             (buffer-string))))))
   #+end_src

   So we can run blocks like these:

   #+begin_example
     ,#+begin_src json :node it.title.toUpperCase()
     {
       "userId": 1,
       "id": 1,
       "title": "delectus aut autem",
       "completed": false
     }
     ,#+end_src

     ,#+RESULTS:
     : DELECTUS AUT AUTEM
   #+end_example

   Enable some languages for code blocks

   #+name: enabling-languages
   #+begin_src emacs-lisp :results none
     (require 'package)
     (org-babel-do-load-languages 'org-babel-load-languages '((shell   . t)))
     (org-babel-do-load-languages 'org-babel-load-languages '((js      . t)))
     (org-babel-do-load-languages 'org-babel-load-languages '((jq      . t)))
     (org-babel-do-load-languages 'org-babel-load-languages '((python  . t)))
     (org-babel-do-load-languages 'org-babel-load-languages '((sql     . t)))
     (org-babel-do-load-languages 'org-babel-load-languages '((http    . t)))
     (org-babel-do-load-languages 'org-babel-load-languages '((awk     . t)))
     (org-babel-do-load-languages 'org-babel-load-languages '((haskell . t)))
   #+end_src

   #+begin_src emacs-lisp :results none
     (with-eval-after-load "json-mode"
       (define-key json-mode-map (kbd "C-c C-j") #'jq-interactively))
   #+end_src

* SQL Settings
  Enable Org-mode babel for SQL

** Sunpower EDP databases

   #+name: SQL argument list
   #+begin_src emacs-lisp :results none
     (setq sql-connection-alist
           '((mds-noprod (sql-product 'postgres)
                         (sql-server "dm1xfz5pr3go5w5.cnnwe8pmnp5z.us-west-2.rds.amazonaws.com")
                         (sql-user "diguzman")
                         (sql-databse "edp_mds"))
             (sot-dev    (sql-product 'postgres)
                         (sql-server "dsxzsf7yo02uin.cnnwe8pmnp5z.us-west-2.rds.amazonaws.com")
                         (sql-user "diguzman")
                         (sql-name "edp_sot"))
             (mds-local  (sql-product 'postgres)
                         (sql-server "localhost")
                         (sql-user "postgres")
                         (sql-name "mds"))
             (sot-local  (sql-product 'postgres)
                         (sql-server "localhost")
                         (sql-user "postgres")
                         (sql-name "sot"))
             ))

     (defun sql-connect-mds-noprod ()
       (interactive)
       (sql-connect 'mds-noprod "*mds-noprod*"))

     (defun sql-connect-sot-dev ()
       (interactive)
       (sql-connect 'sot-dev "*sot-dev*"))

     (add-hook 'sql-interactive-mode-hook
               (lambda ()
                 (toggle-truncate-lines t)))
   #+end_src

* LSP Mode
   #+begin_src emacs-lisp :results none
     (use-package lsp-mode :ensure t)
     (use-package lsp-treemacs :ensure t)

     ;;(add-hook 'c-mode-hook 'lsp)
     ;;(add-hook 'c++-mode-hook 'lsp)
     ;;(add-hook 'python-mode-hook 'lsp)
     (add-hook 'sql-mode-hook 'lsp)
     (setq lsp-sqls-workspace-config-path nil)

     ;(with-eval-after-load 'lsp-mode
     ;  (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
     ;  (yas-global-mode))
   #+end_src

* LSP Java
  Basic instructions to get this configured are hosted on [[https://github.com/emacs-lsp/lsp-java][Github]].

  #+name: enable-lsp-java
  #+begin_src emacs-lisp
    (require 'lsp-java)
    (add-hook 'java-mode-hook #'lsp)
  #+end_src

** Quick start
   Minimal configuration with [[https://github.com/company-mode/company-mode][company-capf]] and [[https://github.com/emacs-lsp/lsp-ui][lsp-ui]] and [[https://github.com/yyoncho/dap-mode/][dap-mode]]. Set
   =lsp-java-workspace-dir= in case you have existing Java
   projects. Now you can explore the methods under =lsp-java-*=,
   =dap-java-*=, =dap-*=, and =lsp-*=.

   #+name: lsp-java-quick-start
   #+begin_src emacs-lisp
     (condition-case nil
         (require 'use-package)
         (file-error
         (require 'package)
         (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
         (package-initialize)
         (package-refresh-contents)
         (package-install 'use-package)
         (setq use-package-always-ensure t)
         (require 'use-package)))

     (use-package projectile)
     (use-package flycheck)
     (use-package yasnippet :config (yas-global-mode))
     (use-package lsp-mode :hook ((lsp-mode . lsp-enable-which-key-integration))
       :config (setq lsp-completion-enable-additional-text-edit nil))
     (use-package hydra)
     (use-package company)
     (use-package lsp-ui)
     (use-package which-key :config (which-key-mode))
     (use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
     (use-package dap-mode :after lsp-mode :config (dap-auto-configure-mode))
     (use-package dap-java :ensure nil)
     (use-package helm-lsp)
     (use-package helm
       :config (helm-mode))
     (use-package lsp-treemacs)
   #+end_src

* Global key settings
Org-mode global keys
- Link store
- Agenda
- Capture

#+begin_src emacs-lisp
(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)
#+end_src

* Load environment variables
I don't know yet what is this for, sorry

#+begin_src emacs-lisp
(when (and (equal emacs-version "27.2") (eql system-type 'darwin))
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))
#+end_src

* Format settings
Set shift width to two columns in general, taken from [[https://emacs.stackexchange.com/questions/45058/emacs-indentation-takes-4-spaces-instead-of-2][stack exchange]].

#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2)
  (setq indent-line-function 'insert-tab)
#+end_src

* Emoji Support
  #+begin_src emacs-lisp :results none
    (add-hook 'after-init-hook #'global-emojify-mode)
  #+end_src
