#+TITLE: EMACS Settings
#+AUTHOR: Diacus Mágnuz
#+STARTUP: logdrawer overview
* Packages
** Add package sources
#+begin_src emacs-lisp
  (package-initialize)
  (require 'package)

  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)

  (package-refresh-contents t)

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
#+end_src
** Package manager straight.el
[[https://github.com/radian-software/straight.el/tree/master][straight.el]] is an alternative package manager that allows installing
Emacs packages directly from their source code repositories. With it
is possible choosing specific versions of the packages to install,
either by branch, fork and even specific commits.

The following code block bootstraps the installation of straight.el,
for details take a look on the [[https://github.com/radian-software/straight.el/tree/master?tab=readme-ov-file#getting-started][Getting started]] section of its
repository.

#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

For a better explaination of this package, take a look at the [[https://systemcrafters.net/advanced-package-management/using-straight-el/][Advanced
Emacs Package Management with straight.el]] article by /SYSTEM
CRAFTERS/.

*** Integration with =use-package=
[[https://github.com/jwiegley/use-package][use-package]] is a macro that provides convenient syntactic sugar for
many common tasks related to installing and configuring Emacs
packages. For details about this integration checkout [[https://github.com/radian-software/straight.el/tree/master?tab=readme-ov-file#integration-with-use-package][this section]].

#+begin_src emacs-lisp
  (straight-use-package 'use-package)
#+end_src

** Add own packages
#+begin_src emacs-lisp
  (defvar personal-packages
    (file-name-concat user-emacs-directory "my-packages")
    "Directory containing custom packages")
  (add-to-list 'load-path personal-packages)
#+end_src

#+begin_example emacs-lisp
  (require 'org-tools)
#+end_example
* Saving and applying customizations
Define a custom file to stroe the settings modified through the
standard customization buffer (=M-x customize RET=).

#+begin_src emacs-lisp
  (setq custom-file
	(file-name-concat user-emacs-directory "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src
* Basic interface setup
Clean and simple interface
#+begin_src emacs-lisp
  (set-scroll-bar-mode nil)
  (tool-bar-mode 0)
  (setq column-number-mode t)
  (unless (equal system-type 'darwin) (menu-bar-mode 0))
#+end_src

File type and mode mapping
#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.env\\'" . conf-mode))
  (add-to-list 'auto-mode-alist '("\\.http\\'" . restclient-mode))
#+end_src

Keep the ring quiet
#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src

* Theme
** Colors for Linux
For Linux, currently I'm using [[https://github.com/cfraz89/arc-dark-theme?tab=readme-ov-file#arc-dark-theme][Arc dark]] theme. Based off
[[https://github.com/jonathanchu/atom-one-dark-theme][jonathanchu/atom-one-dark-theme]] and colors matching [[https://marketplace.visualstudio.com/items?itemName=ph-hawkins.arc-plus][VSCode Arc+]] theme.
#+begin_src emacs-lisp
  (when (eq system-type 'gnu/linux)
    (use-package arc-dark-theme
      :straight (:host github :repo "cfraz89/arc-dark-theme")
      :config (load-theme 'arc-dark t)))
#+end_src

** Colors for MacOs
[[https://github.com/emacsmirror/timu-macos-theme][timu-macos-theme]] is inspired by the macOS UI.
#+begin_src emacs-lisp
  (when (eq system-type 'darwin)
    (use-package timu-macos-theme
      :ensure t
      :init (load-theme 'timu-macos t)))
#+end_src

** Doom modeline
The [[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a fancy and fast mode-line inspired by minimalist
design.
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :hook (after-init . doom-modeline-mode))
#+end_src

For setting up the font family and face, take a look on [[https://stackoverflow.com/questions/6026713/how-do-i-change-emacs-default-font-size-and-font-type][these
instructions]] from Stackoverflow.

* Command line interface
#+begin_src emacs-lisp
  ;; libvterm is not for Windows
  (unless (member system-type '(ms-dos windows-nt cygwin))
    (use-package vterm :ensure t))

  ;; If the operating system is Windows install PowerShell package
  (if (member system-type '(ms-dos windows-nt cygwin))
      (use-package powershell :ensure t))
#+end_src
* Auto completion
Company is a text completion framework for Emacs.
#+begin_src emacs-lisp
  (use-package company :ensure t)
  (company-mode)
  (add-hook 'after-init-hook 'global-company-mode)
#+end_src
* Minibuffer settings
** Ivy
#+begin_example emacs-lisp
  (use-package ivy :ensure t)
  (ivy-mode)
  (setq ivy-use-virtual-buffers t)
  (setq enable-recursive-minibuffers t)
  (global-set-key "\C-s" 'swiper)
  (global-set-key (kbd "C-c C-r") 'ivy-resume)
  (global-set-key (kbd "<f6>") 'ivy-resume)
#+end_example
** Counsel
#+begin_src emacs-lisp
  (use-package counsel :ensure t)
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "<f1> f") 'counsel-describe-function)
  (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
  (global-set-key (kbd "<f1> o") 'counsel-describe-symbol)
  (global-set-key (kbd "<f1> l") 'counsel-describe-find-library)
  (global-set-key (kbd "<f2> i") 'counsel-describe-info-lookup-symbol)
  (global-set-key (kbd "<f2> u") 'counsel-describe-unicode-char)
  (global-set-key (kbd "C-c g") 'counsel-git)
  (global-set-key (kbd "C-c j") 'counsel-git-grep)
  (global-set-key (kbd "C-c k") 'counsel-ag)
  (global-set-key (kbd "C-x l") 'counsel-locate)
  (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
  (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)
#+end_src
** Vertico
#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :init
    (vertico-mode))
#+end_src

** Marginalia
#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    :init
    (marginalia-mode))
#+end_src

** Orderless
This package lets minibuffer use an out-of-order pattern matching
algorithm. It matches space-separated words or regular expressions in
any order.

#+begin_src emacs-lisp
  (use-package orderless
    :ensure t
    :config
    (setq completion-styles '(orderless basic)))
#+end_src

** Consult
Provides lots of commands that are enhanced variants of basic,
built-in functionality. One of the headline features is tis preview
facility, where it shows in another window the context of what is
currently matched in the minibuffer.

#+begin_src emacs-lisp
  (use-package consult
    :ensure t
    :bind
    (("M-s M-g" . consult-grep)     ;; A recursive grep
     ("M-s M-f" . consult-find)     ;; Search for file names recursively
     ("M-s M-o" . consult-outline)  ;; Search through the headlines of a file
     ("M-s M-l" . consult-line)     ;; Search in the current buffer
     ("M-s M-b" . consult-buffer))) ;; Switch to another buffer
#+end_src
* Ledger
#+begin_src emacs-lisp
  (use-package ledger-mode :ensure t)
#+end_src
* GPG
There is a problem wiht GPG, when the key is locked and GPG prompts
for a password in MacOS, it fails with this error:
#+begin_quote
gpg: signing failed: Inappropriate ioctl for device
#+end_quote

I found [[https://stackoverflow.com/questions/57591432/gpg-signing-failed-inappropriate-ioctl-for-device-on-macos-with-maven][this question]] at Stackoverflow that claim to solve it by one
of two ways:
** Seting up environment variable
Add this to the file ~/.bash_profile
#+begin_src shell
  GPG_TTY=$(tty)
  export GPG_TTY
#+end_src
- [[https://github.com/Homebrew/homebrew-core/issues/14737#issuecomment-309848851][source]]

** Using pinentry-mac
Install =pinentry-mac= to have GUI window to enter pin and optionally store it in keychain.

#+begin_src shell
  brew install pinentry-mac
#+end_src

Then enableit with this line in =~/.gnupg/gpg-agent.conf=

#+begin_example
  pinentry-program /usr/local/bin/pinentry-mac
#+end_example

To apply changes kill =gpg-agent=

#+begin_src shell
  killall gpg-agent
#+end_src
* Gptel
#+begin_quote
[[https://github.com/karthink/gptel?tab=readme-ov-file#gptel-a-simple-llm-client-for-emacs][gptel]] isa simple Large Language Model chat client for Emacs, whith
support for multiple models and backends. It works in the spirit of
Emacs, available at any time and uniformly in any buffer.
#+end_quote

You need to get an [[https://platform.openai.com/account/api-keys][OpenAI API Key]] to use GhatGPT, once you get it,
store it in [[file:~/.authinfo.gpg][~/authinfo.gpg]] like this:

#+begin_export ascii
machine api.openaio.com login api_key password YOUR-API-KEY
#+end_export

For [[https://ollama.com][Ollama]] just call =gptel-make-ollama=. See the [[https://github.com/karthink/gptel?tab=readme-ov-file#ollama][documentation]] for
details.

Once you get it enable the following block:
#+begin_src emacs-lisp
  (use-package gptel
    :ensure t
    :config
    ;; Load API Key from ~/.authinfo.gpg
    (setq gptel-api-key
	  (auth-source-pick-first-password
	   :host "api.openai.com"
	   :user "api_key")))

  (gptel-make-ollama
      "Ollama"
    :host "localhost:11434"
    :models
    '(mistral:latest                        ;Simple specs
      openhermes:latest
      (llava:13b                            ;Full spec
       :description
       "Llava 1.6: Large Lanuage and Vision Assistant"
       :capabilities (media)
       :mime-types ("image/jpeg" "image/png")))
    :stream t)
#+end_src

* Password management
GNU [[https://www.passwordstore.org][pass]] is a tool that makes password management simple by following
the [[http://en.wikipedia.org/wiki/Unix_philosophy][UNIX philosophy]].

With =pass= each password lives inside of a =gpg= encrypted text file,
which make it easy to share between devices.

Emacs [[https://github.com/stuartsierra/password-store/tree/master/contrib/emacs][password-store.el]] is a package that provides functions for
working with GNU pass.

#+begin_src emacs-lisp
  (use-package pass :ensure t)
  (use-package password-store :ensure t)
#+end_src

* REST client
#+begin_src emacs-lisp
  (use-package restclient :ensure t)
#+end_src
* Development
** Version control
#+begin_src emacs-lisp
  (use-package magit
    :ensure t
    :config (setq magit-log-arguments '("-n256" "--graph" "--decorate" "--color")
		  magit-diff-refine-hunk t))
#+end_src
** Docker
Add support for managing Docker containers, images, volumes, networks,
contexts and docker-compose

#+begin_src emacs-lisp
  (use-package docker
    :ensure t
    :bind ("C-c d" . docker))
#+end_src

Use =M-x docker=, select a resource then mark or unmark items using
the following keybindings (for more possibilities, check out [[https://github.com/politza/tablist][tablist]]):

| Binding   | Description          |
|-----------+----------------------|
| =?=       | List actions         |
| =l=       | Configure listing    |
| =m=       | MarkItem             |
| =u=       | Unmark item          |
| =t=       | Toggle marks         |
| =U=       | Unmark all           |
| =s=       | Sort                 |
| =* r=     | Mark items by regexp |
| =<=       | Shink column         |
| =>=       | Enlarge column       |
| =C-c C-e= | Export to CSV        |

** Language Server Protocol
#+begin_src emacs-lisp
  (use-package lsp-mode
    :ensure t
    :init
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-c l")
    :hook (;; replace/add XXX-mode with concrete major-mode(e. g. python-mode)
	   (python-mode . lsp)
	   ;; if you want which-key integration
	   (lsp-mode . lsp-enable-which-key-integration))
    :commands (lsp lsp-deferred))

  ;; optionally
  (use-package lsp-ui
    :ensure t
    :commands lsp-ui-mode)

  ;; if you are helm user
  ;; (use-package helm-lsp
  ;;   :ensure t
  ;;   :commands helm-lsp-workspace-symbol)

  ;; if you are ivy user
  (use-package lsp-ivy
    :ensure t
    :commands lsp-ivy-workspace-symbol)

  (use-package lsp-treemacs
    :ensure t
    :commands lsp-treemacs-errors-list)

  ;; optionally if you want to use debugger
  (use-package dap-mode
    :ensure t)
  ;; (use-package dap-LANGUAGE) to load the dap adapter for your language

  ;; optional if you want which-key integration
  (use-package which-key
    :ensure t
    :config (which-key-mode))
#+end_src
** Haskell
See detailed instrucctions [[https://emacs-lsp.github.io/lsp-haskell/][here]].
#+begin_src emacs-lisp
  (use-package haskell-mode :ensure t)
#+end_src emacs-lisp

#+begin_example emacs-lisp
  (use-package lsp-haskell
    :ensure t
    :hook ((haskell-mode          . lsp)
	   (haskell-literate-mode . lsp)))
#+end_example

** Python
:REFERENCES:
- [[https://emacs-lsp.github.io/lsp-pyright/][LSP Pyright]]
:END:
#+begin_example emacs-lisp
  (use-package lsp-pyright
    :ensure t
    :hook (python-mode . (lambda ()
			   (require 'lsp-pyright (lsp)))))
#+end_example
* Orgmode
Jump to heading, as describes at [[https://stackoverflow.com/questions/15011703/is-there-an-emacs-org-mode-command-to-jump-to-an-org-heading][Stackoverflow]]
#+begin_src emacs-lisp
  (setq org-goto-interface 'outline-path-completion
	org-goto-max-level 10)
  (setq org-outline-path-complete-in-steps nil)
#+end_src

Org bullets
#+begin_src emacs-lisp
  (use-package org-bullets :ensure t)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

Orgmode babel loading languages
#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages '((shell . t)))
#+end_src

* Emulate Vim editing style
Evil is an extensible vi layer for Emacs, plus [[https://github.com/emacs-evil/evil-collection][evil-collection]] package
installs a collection of Evil bindings for the parts of Emacs that
Evil doest not cover property by default, such as =help-mode=, =M-x
calendar=, Eshell and more.

See Evil Collection repository for details.

#+begin_src emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    :config
    (evil-mode 1))

  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))
#+end_src

* Major mode hooks
Every buffer posses a [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html][major mode]], which determines the editing
behavior of Emacs while that buffer is current.

Every major mode, apart from =Fundamental mode=, defines a /mode
hook/, a customizable list of Lisp functions to run each time the mode
is enabled in a buffer. See [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Hooks.html][Hooks]], for more information about hooks.

All text-based major modes run =text-mode-hook=, and many programming
language modes (see [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Derived-Modes.html#Derived-Modes][Derived Modes]] for details) run =prog-mode-hook=
prior running their own mode hooks.

** Prog mode
=hl-line-mode= to highlights the cursor line. Then customize the
*Highlight* face to teak the look and feel as you need.
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'hl-line-mode)
#+end_src

=display-line-numbers-mode= numbers the lines in the buffer. Set
relative numbering by customizing =display-line-numbers-type=
variable.
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

** Perl
[[http://xahlee.info/emacs/emacs/emacs_perl_vs_cperl_mode.html][CPerl mode]] is an enhanced mode for Perl development. It was designed
to provide better suppor for Perl's syntax and features, specially for
more complex code.

By customizing =interpreter-mode-alist=, it is possible make Emacs
recognize Perl scripts based on their shebang line, even if they lack
a specific file extension.

#+begin_src emacs-lisp
  (add-to-list 'interpreter-mode-alist '("perl"     . cperl-mode))
  (add-to-list 'interpreter-mode-alist '("perl5"    . cperl-mode))
  (add-to-list 'interpreter-mode-alist '("miniperl" . cperl-mode))
  (add-to-list 'auto-mode-alist '("\\.\\([pP][Llm]\\|al\\)\\'" . cperl-mode))
  (add-to-list 'auto-mode-alist '("\\.[tT]\\'" . cperl-mode)) ; For .t files (Perl test files)
#+end_src

The following hook settings are based on the [[https://dev.to/nicholasbhubbard/how-i-use-emacs-to-write-perl-40e6]["How I use Emacs to write
Perl"]] post.
#+begin_src emacs-lisp
  (require 'flycheck)
  (use-package inf-perl
    :straight (:host github :repo "nverno/inf-perl"))

  (defun cperl-mode-custom-settings ()
    (setq cperl-indent-level 2)
    (setq cperl-indent-parens-as-block t)
    (setq flycheck-check-syntax-automatically '(mode-enabled save))
    (setq flycheck-display-errors-delay 0.3))

  (defun cperl-mode-key-bindings ()
    (define-key cperl-mode-map (kbd "C-c C-z") 'inf-perl-run))

  (add-hook 'cperl-mode-hook 'flycheck-mode)
  (add-hook 'cperl-mode-hook 'cperl-mode-custom-settings)
  (add-hook 'cperl-mode-hook 'cperl-mode-key-bindings)
#+end_src

* References
- [[https://protesilaos.com/codelog/2024-02-17-emacs-modern-minibuffer-packages/][Emacs modern minibuffer packages]]
