#+TITLE: EMACS Settings
#+AUTHOR: Diacus Mágnuz
#+STARTUP: logdrawer latexpreview
* Packages
** Add package sources
#+begin_src emacs-lisp
  (package-initialize)
  (require 'package)

  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)

  (package-refresh-contents t)

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
#+end_src
** Quelpa package manager
Install Emacs packages directly from source, for more information
about installation and usage see its [[https://github.com/quelpa/quelpa][repository]] at Github. The
following snippet bootstraps Quelpa automatically.
#+begin_src emacs-lisp
  (use-package quelpa :ensure t)
#+end_src

Quelpa integrates with =use-package= with a handler provided by
=quelpa-use-package=.
#+begin_src emacs-lisp
  (quelpa
   '(quelpa-use-package
     :fetcher git
     :url "https://github.com/quelpa/quelpa-use-package.git"))
  (require 'quelpa-use-package)
#+end_src

** Add own packages
#+begin_src emacs-lisp
  (defvar personal-packages
    (file-name-concat user-emacs-directory "my-packages")
    "Directory containing custom packages")
  (add-to-list 'load-path personal-packages)
#+end_src

#+begin_example emacs-lisp
  (require 'org-tools)
#+end_example
* Theme
** Cursor line
By default the cursorline hightlighting is underlined, I don't like it.
#+begin_src emacs-lisp
   (use-package hl-line
     :config
     (set-face-underline 'hl-line nil))
#+end_src

** Colors for Linux and BSD
Installing Nord theme included in [[https://github.com/doomemacs/themes?tab=readme-ov-file#manually--use-package][doom-themes]] collection
#+begin_src emacs-lisp
  (when (member system-type '(gnu/linux berkeley-unix))
    (use-package doom-themes
      :ensure t
      :config
      ;; Global settings (defaults)
      (setq doom-themes-enable-bold t
  	  doom-themes-enable-italic t)
      (load-theme 'doom-nord :no-confirm)))
#+end_src

** Colors for MacOs
[[https://github.com/emacsmirror/timu-macos-theme][timu-macos-theme]] is inspired by the macOS UI.
#+begin_src emacs-lisp
  (when (eq system-type 'darwin)
    (use-package timu-macos-theme
      :ensure t
      :init (load-theme 'timu-macos t)))
#+end_src

** Doom modeline
The [[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a fancy and fast mode-line inspired by minimalist
design.
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :hook (after-init . doom-modeline-mode))
#+end_src

For setting up the font family and face, take a look on [[https://stackoverflow.com/questions/6026713/how-do-i-change-emacs-default-font-size-and-font-type][these
instructions]] from Stackoverflow.

* Basic interface setup
Clean and simple interface
#+begin_src emacs-lisp
  (set-scroll-bar-mode nil)
  (tool-bar-mode 0)
  (setq column-number-mode t)
#+end_src

Instead of the default init screen, check out this [[https://github.com/emacs-dashboard/emacs-dashboard?tab=readme-ov-file#emacs-dashboard][Emacs Dashboard]].
#+begin_src emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (setq dashboard-startup-banner 'logo)
    (setq dashboard-items '((agenda   . 5)
			    (projects . 5)
			    (recents  . 5)))
    (dashboard-setup-startup-hook))
#+end_src

File type and mode mapping
#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.env\\'" . conf-mode))
#+end_src

Keep the ring quiet
#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src

* File Management
Use Emacs as a file manager with =dired=. Enable the follwing setting
to copy/move files between distant directories. [[https://emacs.stackexchange.com/questions/5603/how-to-quickly-copy-move-file-in-emacs-dired][Source]].

#+begin_src emacs-lisp
  (setq dired-dwim-target 1)
#+end_src

* Emulate Vim editing style
Evil is an extensible vi layer for Emacs, plus [[https://github.com/emacs-evil/evil-collection][evil-collection]] package
installs a collection of Evil bindings for the parts of Emacs that
Evil doest not cover property by default, such as =help-mode=, =M-x
calendar=, Eshell and more.

See Evil Collection repository for details.

#+begin_src emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    :config
    (evil-mode 1))

  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))
#+end_src

* Auto completion
[[https://company-mode.github.io/][Company]] is a text and code completion framework for Emacs. It uses
pluggable backends and frontends to retreive and display completion
candidates.
#+begin_src emacs-lisp
  (use-package company
    :ensure t
    :hook (after-init . global-company-mode)
    :init (company-mode))
#+end_src
* Minibuffer settings
** Vertico
The [[https://github.com/minad/vertico][vertico]] package applies vertical layout to the minibuffer. It also
pops up the minibuffer eagerly so we can see the available options
without further integrations.
#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :init
    (vertico-mode))
#+end_src

** Marginalia
The [[https://elpa.gnu.org/packages/marginalia.html][marginalia]] package provides informative margin annotations to the
minibuffer completions.
#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    :init
    (marginalia-mode))
#+end_src

** Ivy
[[https://github.com/abo-abo/swiper?tab=readme-ov-file#ivy][Ivy]] is a generic completion mechanism for Emacs. While it operates
similary to other completion schemes, aims to be more efficient,
smaller, simpler and smoother to use yet highly customizable.
#+begin_src emacs-lisp
  (use-package ivy
    :ensure t
    :config
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)                               ; Enable virtual buffers
    (setq ivy-count-format "(%d/%d) ")                             ; Customize the display format
    (setq ivy-re-builders-alist '((t . ivy--regex-ignore-order)))  ; Improve matching
    ;; Customize Ivy appearance
    (setq ivy-height 10)                                           ; Number of lines in minibuffer
    (setq ivy-format-function 'ivy-format-function-arrow)          ; Use arrows for candidates
    (setq ivy-display-style 'fancy)                                ; Fancy display style
    (setq ivy-initial-inputs-alist nil))                           ; Disable initial input
#+end_src
** Counsel
#+begin_src emacs-lisp
  (use-package counsel
    :ensure t
    :after ivy
    :config
    (counsel-mode 1))
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "<f1> f") 'counsel-describe-function)
  (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
  (global-set-key (kbd "<f1> o") 'counsel-describe-symbol)
  (global-set-key (kbd "<f1> l") 'counsel-describe-find-library)
  (global-set-key (kbd "<f2> i") 'counsel-describe-info-lookup-symbol)
  (global-set-key (kbd "<f2> u") 'counsel-describe-unicode-char)
  (global-set-key (kbd "C-c g") 'counsel-git)
  (global-set-key (kbd "C-c j") 'counsel-git-grep)
  (global-set-key (kbd "C-c k") 'counsel-ag)
  (global-set-key (kbd "C-x l") 'counsel-locate)
  (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
  (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)
#+end_src
** Consult
The [[https://github.com/minad/consult][consult]] package provides lots of commands that are enhanced
variants of basic, built-in functionality. One of the headline
features is tis preview facility, where it shows in another window the
context of what is currently matched in the minibuffer.
#+begin_src emacs-lisp
  (use-package consult
    :ensure t
    :bind
    (("M-s M-g" . consult-grep)     ;; A recursive grep
     ("M-s M-f" . consult-find)     ;; Search for file names recursively
     ("M-s M-o" . consult-outline)  ;; Search through the headlines of a file
     ("M-s M-l" . consult-line)     ;; Search in the current buffer
     ("M-s M-b" . consult-buffer))) ;; Switch to another buffer
#+end_src

Consult with LSP:
#+begin_src emacs-lisp
  (use-package consult-lsp
    :ensure t
    :after lsp-mode)
#+end_src

** Orderless
This package lets minibuffer use an out-of-order pattern matching
algorithm. It matches space-separated words or regular expressions in
any order.

#+begin_src emacs-lisp
  (use-package orderless
    :ensure t
    :config
    (setq completion-styles '(orderless basic)))
#+end_src

** Which-key
When working in Emacs, we used to use complex keybindings to access
various functions and commands. [[https://systemhalted.in/emacs/emacs-which-key/][which-key]] is a package that provides a
pop-up window that displays available keybindings and their associated
commands.
#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :config
    (which-key-mode))
#+end_src
** References
- [[https://protesilaos.com/codelog/2024-02-17-emacs-modern-minibuffer-packages/][Emacs modern minibuffer packages]]
* Saving and applying customizations
Define a custom file to stroe the settings modified through the
standard customization buffer (=M-x customize RET=).

#+begin_src emacs-lisp
  (setq custom-file
	(file-name-concat user-emacs-directory "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src

* Command line interface
** vterm
Emacs-libvterm ([[https://github.com/akermu/emacs-libvterm][vterm]]) is a fully-fleged terminal emulator inside GNU
Emacs based on [[https://github.com/neovim/libvterm][libvterm]], a C library (UNIX like systems only)
#+begin_src emacs-lisp
  (unless (member system-type '(ms-dos windows-nt cygwin))
    (use-package vterm
      :ensure t
      :config
      (evil-define-key
	'(normal visual)
	'global
	(kbd "SPC o t")
	'vterm-other-window)))

  (defun my/delete-vterm-window-on-exit (buffer _status)
    "Delete vterm window when the shell process exits.
  BUFFER is the vterm buffer, STATUS is the exit message."
    (when (buffer-live-p buffer)
      (with-current-buffer buffer
	(when (and vterm--process (not (process-live-p vterm--process)))
	  ;; Kill the buffer first to avoid window errors
	  (let ((window (get-buffer-window buffer)))
	    (kill-buffer buffer)
	    ;; only delete window if it exists and isn´t the only window
	    (when (and window (not (one-window-p)))
	      (delete-window window)))))))

  (add-hook 'vterm-exit-functions #'my/delete-vterm-window-on-exit)
#+end_src

The [[https://github.com/suonlight/multi-vterm][multi-vterm.el]] package allows managing multiple =vterm= buffers.
#+begin_src emacs-lisp
  (use-package multi-vterm
    :ensure t
    :after vterm
    :config
    (evil-define-key '(normal visual) 'global (kbd "SPC o T") 'multi-vterm))
#+end_src

** powershell
If the operating system is Windows install PowerShell package
#+begin_src emacs-lisp
  (when (member system-type '(ms-dos windows-nt cygwin))
      (use-package powershell :ensure t))
#+end_src

* Ledger
#+begin_src emacs-lisp
  (use-package ledger-mode :ensure t)
#+end_src
* GPG
Setting the value of =epg-pinentry-mode= to =loopback= allows Emacs to
query the passphrase throught minibuffer.
#+begin_src emacs-lisp
  (setq epg-pinentry-mode 'loopback)
#+end_src

* Gptel
#+begin_quote
[[https://github.com/karthink/gptel?tab=readme-ov-file#gptel-a-simple-llm-client-for-emacs][gptel]] is a simple Large Language Model chat client for Emacs, whith
support for multiple models and backends. It works in the spirit of
Emacs, available at any time and uniformly in any buffer.
#+end_quote

You need to get an [[https://platform.openai.com/account/api-keys][OpenAI API Key]] to use GhatGPT, once you get it,
store it in [[file:~/.authinfo.gpg][~/authinfo.gpg]] like this:

#+begin_export ascii
machine api.openaio.com login api_key password YOUR-API-KEY
#+end_export

For [[https://ollama.com][Ollama]] just call =gptel-make-ollama=. See the [[https://github.com/karthink/gptel?tab=readme-ov-file#ollama][documentation]] for
details.

Once you get it enable the following block:
#+begin_src emacs-lisp
  (use-package gptel
    :ensure t
    :config
    ;; Load API Key from ~/.authinfo.gpg
    (setq gptel-api-key
	  (auth-source-pick-first-password
	   :host "api.deepseek.com"
	   :user "api_key"))
    (setq gpt-backend
	  (gptel-make-openai "DeepSeek"
	    :host "api.deepseek.com"       ; DeepSeek API host
	    :endpoint "/chat/completions"  ; DeepSeek API endpoint
	    :models '("deepseek-chat")     ; Model name(s)
	    :key (auth-source-pick-first-password
		  :host "api.deepseek.com"
		  :user "api_key"))))

  (gptel-make-ollama
      "Ollama"
    :host "localhost:11434"
    :models
    '(mistral:latest                        ;Simple specs
      openhermes:latest
      (llava:13b                            ;Full spec
       :description
       "Llava 1.6: Large Lanuage and Vision Assistant"
       :capabilities (media)
       :mime-types ("image/jpeg" "image/png")))
    :stream t)
#+end_src

* Password management
GNU [[https://www.passwordstore.org][pass]] is a tool that makes password management simple by following
the [[http://en.wikipedia.org/wiki/Unix_philosophy][UNIX philosophy]].

With =pass= each password lives inside of a =gpg= encrypted text file,
which make it easy to share between devices.

Emacs [[https://github.com/stuartsierra/password-store/tree/master/contrib/emacs][password-store.el]] is a package that provides functions for
working with GNU pass.

#+begin_src emacs-lisp
  (use-package pass :ensure t)
  (use-package password-store :ensure t)
#+end_src

* REST client
#+begin_src emacs-lisp
  (use-package restclient :ensure t)
  (add-to-list 'auto-mode-alist '("\\.http\\'" . restclient-mode))

  (use-package ob-restclient :ensure t)
#+end_src

* IA Integration
#+begin_src emacs-lisp
  (use-package gptel
    :ensure t
    :config
    ;; Configurar backend de Ollama correctamente
    (setq gptel-backend
	  (gptel-make-ollama
	    "ollama"         ;; Nombre del backend
	    :protocol "http"
	    :host "localhost:11434"                   ;; Puerto por defecto de Ollama
	    :models '("codellama:latest" "deepseek-coder:latest" "llama3:latest")
	    :stream t)) 
    (setq gptel-model "codellama:latest"))
#+end_src

* Development
** Projectile
[[https://docs.projectile.mx/projectile/index.html][Projectile]] is a project integration library for Emacs. Its goal is to
provide features operating on a project level without introducing
external dependencies (when feasable).
#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :config
    (evil-define-key 'normal 'global (kbd "SPC p p") 'projectile-switch-project)
    (evil-define-key 'normal 'global (kbd "SPC p k") 'projectile-kill-buffers)
    (evil-define-key 'normal 'global (kbd "SPC p f") 'projectile-find-file)
    (evil-define-key 'normal 'global (kbd "SPC p F") 'projectile-find-file-other-frame)
    (evil-define-key 'normal 'global (kbd "SPC p b") 'projectile-switch-to-buffer)
    (evil-define-key 'normal 'global (kbd "SPC p B") 'projectile-switch-to-buffer-other-frame)
    (projectile-mode +1)
    (setq projectile-completion-system 'ivy))
#+end_src
** Prog mode
Many programming language modes (see [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Derived-Modes.html#Derived-Modes][Derived Modes]] for details) run
=prog-mode-hook= prior running their own mode hooks. So this is a good
place to define settings common for use with any programming language.
#+begin_src emacs-lisp
  (defun prog-mode-key-bindings()
    "Define key bindings useful for prog-mode"
    (evil-define-key
      '(normal visual motion) prog-mode-map (kbd "SPC o r") 'vterm-other-window))

  (add-hook 'prog-mode-hook 'prog-mode-key-bindings)
#+end_src

For syntax checking, [[https://www.flycheck.org/en/latest/][Flycheck]] is a modenr on-the-fly syntax checking
extension for GNU Emacs, intended as replacement for the older Flymake
extension which is part of GNU Emacs.
#+begin_src emacs-lisp
  (use-package flycheck :ensure t)

  (defun prog-mode-custom-settings ()
    "Settings for all programming languages"
    (setq flycheck-check-syntax-automatically '(mode-enabled save))
    (setq flycheck-display-errors-delay 0.3))
  
  (add-hook 'prog-mode-hook 'flycheck-mode)
  (add-hook 'prog-mode-hook 'prog-mode-custom-settings)
#+end_src

=hl-line-mode= to highlights the cursor line. Then customize the
*Highlight* face to teak the look and feel as you need.
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'hl-line-mode)
#+end_src

=display-line-numbers-mode= numbers the lines in the buffer. Set
relative numbering by customizing =display-line-numbers-type=
variable.
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

** Version control
*** Magit
[[https://magit.vc/][Magit]] is a complete text based user interface to [[https://git-scm.com/][Git]].
#+begin_src emacs-lisp
  (use-package magit
    :ensure t
    :config
    (evil-define-key 'normal 'global (kbd "SPC g g") 'magit)
    (evil-define-key 'normal 'global (kbd "SPC g f") 'magit-find-file)
    (evil-define-key 'normal 'global (kbd "SPC g F") 'magit-find-file-other-frame)
    (evil-define-key 'normal 'global (kbd "SPC g l") 'magit-log-current)
    (evil-define-key 'normal 'global (kbd "SPC g t") 'magit-log-all-branches)
    (setq
     magit-log-arguments '("-n256" "--graph" "--decorate" "--color")
     magit-diff-refine-hunk t))
#+end_src

** Docker
Add support for managing Docker containers, images, volumes, networks,
contexts and docker-compose

#+begin_src emacs-lisp
  (use-package docker
    :ensure t
    :bind ("C-c d" . docker))
#+end_src

Use =M-x docker=, select a resource then mark or unmark items using
the following keybindings (for more possibilities, check out [[https://github.com/politza/tablist][tablist]]):

| Binding   | Description          |
|-----------+----------------------|
| =?=       | List actions         |
| =l=       | Configure listing    |
| =m=       | MarkItem             |
| =u=       | Unmark item          |
| =t=       | Toggle marks         |
| =U=       | Unmark all           |
| =s=       | Sort                 |
| =* r=     | Mark items by regexp |
| =<=       | Shink column         |
| =>=       | Enlarge column       |
| =C-c C-e= | Export to CSV        |
** Language Server Protocol
The client for [[https://github.com/Microsoft/language-server-protocol/][Language Server Protocol]], [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] aims to provide
IDE-like experience by providing optional integration with the most
popular Emacs packages like =company=, =flycheck= and =projectile=.
#+begin_src emacs-lisp
  (use-package lsp-mode
    :ensure t
    :hook (haskell-mode . lsp)
    :commands lsp)
#+end_src
** Python
Use [[https://github.com/aiguofer/pyenv.el][pyenv.el]] to manage your Python version within Emacs using pyenv
#+begin_src emacs-lisp
  (use-package pyenv
    :quelpa (pyenv :fetcher github :repo "aiguofer/pyenv.el")
    :hook (python-mode . global-pyenv-mode))
#+end_src
*** Virtual environments
#+begin_src emacs-lisp
  (use-package pyvenv
    :ensure t
    :hook (python-mode . pyvenv-mode))
#+end_src

** Perl
[[http://xahlee.info/emacs/emacs/emacs_perl_vs_cperl_mode.html][CPerl mode]] is an enhanced mode for Perl development. It was designed
to provide better suppor for Perl's syntax and features, specially for
more complex code.

By customizing =interpreter-mode-alist=, it is possible make Emacs
recognize Perl scripts based on their shebang line, even if they lack
a specific file extension.

#+begin_src emacs-lisp
  (add-to-list 'interpreter-mode-alist '("perl"     . cperl-mode))
  (add-to-list 'interpreter-mode-alist '("perl5"    . cperl-mode))
  (add-to-list 'interpreter-mode-alist '("miniperl" . cperl-mode))
  (add-to-list 'auto-mode-alist '("\\.\\([pP][Llm]\\|al\\)\\'" . cperl-mode))
  (add-to-list 'auto-mode-alist '("\\.[tT]\\'" . cperl-mode)) ; For .t files (Perl test files)
#+end_src

Perl Debugger
#+begin_src emacs-lisp
  (defun spawn-run-perl-debugger-with-stdin ()
    "Run the Perl debugger on the current file with output from another file."
    (interactive)
    (let* ((perl-file  (buffer-file-name))
	   (input-file (read-file-name "Input file: ")))
      (if (and perl-file input-file)
	  (progn
	    (split-window-below)
	    (other-window 1)
	    (let ((buffer (get-buffer-create "*perl-debugger*")))
	      (with-current-buffer buffer
		(comint-mode)
		(erase-buffer)
		(insert (format "Starting Perl debugger for %s with input from %s\n" perl-file input-file))
		(make-comint "perl-debugger" "perl" nil "-d" perl-file)
		(comint-send-string buffer (format "open(STDIN, '<%s') or die $!;\n" input-file)))
	      (switch-to-buffer buffer)))
	(message "No file is associated with this buffer or not imput selected"))))
#+end_src

The following hook settings are based on the [[https://dev.to/nicholasbhubbard/how-i-use-emacs-to-write-perl-40e6]["How I use Emacs to write
Perl"]] post.
#+begin_src emacs-lisp
  (use-package inf-perl
    :quelpa (inf-perl :fetcher github :repo "nverno/inf-perl"))

  (defun cperl-mode-custom-settings ()
    (setq cperl-indent-level 2)
    (setq cperl-indent-parens-as-block t))

  (defun cperl-mode-key-bindings ()
    (define-key cperl-mode-map (kbd "C-c C-z") 'inf-perl-run)
    (define-key cperl-mode-map (kbd "C-c C-d") 'spawn-run-perl-debugger-with-stdin))

  (add-hook 'cperl-mode-hook 'cperl-mode-custom-settings)
  (add-hook 'cperl-mode-hook 'cperl-mode-key-bindings)
#+end_src

** Haskell
The [[https://wiki.haskell.org/Emacs][haskell-mode]] package is a set of major modes for writing Haskell
code and working with Haskell projects. Features syntax hightlighting,
intelligent indentation, interaction with inferior Haskel interpreter,
code browsing, and Cabal project integration. It supports Hugs, GHCi,
Cabal, hslint, hoogle, cabal-dev and other utilities. See the [[http://haskell.github.io/haskell-mode/manual/latest/][Haskell
Mode manual]] for more details.
#+begin_src emacs-lisp
  (use-package haskell-mode :ensure t)
#+end_src

*** Compilation
The *haskell-mode* includes an specialized /compilation mode/ with
additional features called [[http://haskell.github.io/haskell-mode/manual/latest/Compilation.html#Compilation][haskell-compile]]. When invoked it tries to
guess how to compile the program associated to the current buffer.
#+begin_src emacs-lisp
  (add-hook
   'haskell-mode-hook
   (lambda ()
     (evil-define-key '(normal visual motion) haskell-mode-map (kbd "SPC o r") 'haskell-interactive-bring)
     (evil-define-key '(normal visual motion) haskell-mode-map (kbd "SPC c c") 'haskell-compile)))

  (add-hook
   'haskell-cabal-mode-hook
   (lambda ()
     (evil-define-key '(normal visual motion) haskell-cabal-mode-map (kbd "C-`") 'haskell-interactive-bring)
     (evil-define-key 'normal haskell-cabal-mode-map (kbd "SPC c c") 'haskell-compile)))
#+end_src

*** Language Server
The [[https://haskell-language-server.readthedocs.io/en/latest/what-is-hls.html][Haskell Language Server (HLS)]] is an implementation of a server for
[[https://microsoft.github.io/language-server-protocol/][LSP]] 

See detailed instrucctions [[https://emacs-lsp.github.io/lsp-haskell/][here]].
#+begin_src emacs-lisp
  (use-package lsp-haskell
    :ensure t
    :after lsp-mode
    :config
    (setq lsp-haskell-process-path-hie "haskell-language-server-wrapper")
    (setq lsp-haskell-process-args-hie '()))
#+end_src
* Writing
** TeX
For $\TeX$ and $\LaTeX$ use *AUCTeX*, a program offering many featues
and configuration options. Take a look to its [[https://www.gnu.org/software/auctex/manual/auctex.html#Editing-Facilities][quick start]] guide for
details.
#+begin_src emacs-lisp
  (use-package tex
    :ensure auctex
    :config
    (setq-default TeX-master nil)
    (setq TeX-auto-save t)
    (setq TeX-parse-self t))
#+end_src

*** Filling
#+begin_src emacs-lisp
  (add-hook 'LaTeX-mode-hook #'turn-on-auto-fill)
#+end_src

Also check [[https://tex.stackexchange.com/questions/50827/a-simpletons-guide-to-tex-workflow-with-emacs][this]] question in StackExchange.

** Orgmode
Jump to heading, as describes at [[https://stackoverflow.com/questions/15011703/is-there-an-emacs-org-mode-command-to-jump-to-an-org-heading][Stackoverflow]]
#+begin_src emacs-lisp
  (setq org-goto-interface 'outline-path-completion
	org-goto-max-level 10)
  (setq org-outline-path-complete-in-steps nil)
#+end_src

Disable flycheck in =org-src= mode
#+begin_src emacs-lisp
  (add-hook 'org-src-mode-hook (lambda () (flycheck-mode -1)))
#+end_src

Include =.org.gpg= files in =org-agenda-files= following [[https://emacs.stackexchange.com/questions/36542/include-org-gpg-files-in-org-agenda][StackExchange
(emacs) answer]]

#+begin_src emacs-lisp
  (unless (string-match-p "\\.gpg" org-agenda-file-regexp)
    (setq org-agenda-file-regexp "\\`[^.].*\\.org\\\(\\.gpg\\\)?\\'"))
#+end_src

*** Evil Org
[[https://github.com/Somelauw/evil-org-mode][evil-org]] package adds key-bindings to Emacs org-mode
#+begin_src emacs-lisp
  (use-package evil-org
    :ensure t
    :after org
    :hook (org-mode . evil-org-mode)
    :config
    (require 'evil-org-agenda)
    (evil-org-agenda-set-keys))
#+end_src

If Emacs runs inside a terminal, =TAB= key might not work as expected
(being bound to =evil-jump-forward= instead of =org-tab= or
=org-cycle=).

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook
	    (lambda ()
	      ;; Only apply this in terminal mode
	      (unless (display-graphic-p)
		;; Prevent Evil from binding C-i (Tab) to evil-jump-forward
		(setq evil-want-C-i-jump nil)
		;; Bind TAB to org-cycle in normal state
		(evil-define-key 'normal 'global (kbd "TAB") 'org-cycle))))
#+end_src

*** Org bullets
#+begin_src emacs-lisp
  (use-package org-bullets
    :ensure t
    :after org)

  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

*** Orgmode babel
Org [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][Babel]] supports a growing number of programming languages.
#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((awk        . t)
     (dot        . t)
     (haskell    . t)
     (js         . t)
     (python     . t)
     (restclient . t)
     (shell      . t)
     (sql        . t)))
#+end_src
